language: python
python:
- '2.7'
install: pip install -r requirements.pip
script: bash ./run_coverage.sh
deploy:
  provider: pypi
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  username:
    secure: vP/+AlI4on6cUFCLfe/OYCYAHZQ83dw3mqZdQB07sgW2ucbu7oCj7aUglW+ljvAvZm7SE1ZJWXqmdPom76d9LcF4KIGhTnlmLV1E6ixPVZR7H8hdQsST8fHrk2Ml1Ax4aCzKIXsdcS3+DvR2G/FtIoGzTCQIG2+b78N/OxkHYoUgudtpXS0/8jbN9kE3Ev/wH5/aQ1y5sjlPBDHRon93l/DPTidNY5B2+aFvTulyYDKw9w50vtbh67ULu30tyxB7uRGxNs0zc050q+jmgYoA6PrCCcX7uXzk6fY9Nt3oi5Pm6ZjU9zj9PH8g/8Mw1cWyz+68PyhHD4U+fez2o7YXgImugo9T/Ph5X7to6wZgXIb/e19YKgt4eJcOAhDtFeHyK1AFHQUduw+7UoSYbYn85yeRaIjmeIPcFWdYMSw+PZbpTVE4lPt+B4FahI8QW8xIT/NRQgRE84vLJISZXT0niG2ggIqOw//YHxIH2RXH5h3zZ+F/xqk/ABeAnoA6V3CchYyewBLh84NZoq9svMARRSgHyiHq4qUqodFigIYFrii1SUpq+IhlHmA/u6jYHzdyxZu2eLIihNeD++IM1S6UnRaI30Tr2H+sDfoa5Q01gnvsZ7y3JVgzunihcbvMiJZkmriFi9vSy3NKhm1DOKi3RFppNgy4SKINjoZ7oK3CkTM=
  password:
    secure: S5JSVcSjUtrSX5BvehBog7k6MrS0YJBTaQhJlxVLEd00TgBkFu09ZlvHrWD+U1Aizk3j53cdPOKFM2K5CoAgfQY69hbq/N2th/m65++4BuNh8BbQ1y/7D0qhwe0il5MGT70ValaCXVRqQtRcMt13mGBPsAs8pijHCblzX5g4qITW8bF7QIz5crdrVL4iCc8sKn4N2AkLpdjczVqj5aiRnwuQ92Nv3wkOkDRsuixLizwvHVDeudr77R38F1bmPnm8qS2MXnHhv+4YbcChiVpqZSij2Osu07RSno6492XkA1MxOl/Dq4k/BymajRzxUff1EgmGGDv3PCcLUP++4FNYVRognv29kWaXhjLnj9+3tyrAGmIUXnsibYFIbzkShOIG3kM1gsQH/HAplgI/wQkF+1rpQap5gXkmTnHfc8DuqvuZEIirVjHuvZZ4AwvF5QaUM+hTe+5lcFCX+p0sdzxvwxnom/MnHUvy6LyZwDC1dtVg3pN0Z9V+pZFAsS6fCOqr6O4ArnmpORA+/fvPGbeuxZ145IPehhSHb/Rh0dsVfn1ed1qzGe+a066MUps3OTJTK86JmrwvU9Hd3q3L5/8A4ezs1hEozh2jvRuuGMHGJUd4UmnNNVzIgozbGmSGij3EpFgAcRXPQ/Vcd5ms/AoWYilbuK0WDMYBhc+BWX4EKN8=
after_success:
- coveralls
